apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-go
  namespace: inference
  labels: { app: inference-go }
spec:
  replicas: 2
  selector:
    matchLabels: { app: inference-go }
  template:
    metadata:
      labels: { app: inference-go }
    spec:
      terminationGracePeriodSeconds: 20
      containers:
        - name: server
          image: inference-go:latest
          imagePullPolicy: IfNotPresent
          ports:
            - { name: grpc, containerPort: 50051 }
          envFrom:
            - configMapRef: { name: inference-config }
          resources:
            requests: { cpu: "100m", memory: "32Mi" }
            limits:   { cpu: "1",    memory: "128Mi" }
          readinessProbe:
            grpc: { port: 50051 }
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            grpc: { port: 50051 }
            initialDelaySeconds: 5
            periodSeconds: 10
